### ISSUE TITLE
Biomes dont generate in End

### ISSUE THREAD

**Issue by SugarDaddii** [team-abnormals/endergetic#141]
Hey i dont know if this related to you but in my End spawing gravel beaches! 
and nothing of your mod is spawning in the END!

https://imgur.com/a/l9Ccls7

**Comment by SmellyModder** [comment]
This issue gets caused by biome IDs getting shifted and is not necessarily an Endergetic issue. This can happen when biomes are removed or added to the biome registry. It's difficult to pinpoint what mod exactly is causing the shifting, and even data packs can cause shifts to occur. There have even been times where Poise Forests and other modded biomes that generate in specific dimensions generating in the overworld.
