### ISSUE TITLE
[Suggestion] Have puff bugs come out at night in the overworld

### ISSUE THREAD

**Issue by MarioSMB** [team-abnormals/endergetic#164]
This is a rather minor detail, but it could be a nice touch to have the puff bugs only come out of their hive at night when placed in the overworld, similar to how bees come out during the day and retreat to their hive at night.

**Comment by SmellyModder** [comment]
Puff Bugs are efficient workers, and their pollinating is already limited by them sleeping occasionally.
Also, Puff Bugs hives can be used as traps, and having them sleep at night would limit this.

Because of these reasons, I don't think it'd be a good idea. Also, just my opinion, but I think the Puff Bugs being more different when compared to the Bees is a good thing because it adds to their 'alien' feel.
I appreciate the suggestion though 🙂
