### ISSUE TITLE
[1.16.5] Server tick took over 60 seconds

### ISSUE THREAD

**Issue by GAsplund** [team-abnormals/endergetic#176]
I have determined that this mod is causing our server to crash after analyzing our crash reports and looking into the mixins involved. The functions this mod calls in the spawnBalloons method clearly matches the stack trace.

I have attached my crash log.
[crashlog.txt](https://github.com/team-abnormals/endergetic/files/6604020/crashlog.txt)

**Comment by SmellyModder** [comment]
The crash you have sent doesn't relate to the `spawnBalloons()` method.

The last method called in the stack trace that isn't a writing operation is `func_237335_a_()`.
`func_237335_a_()` is `PlayerData#savePlayerData()`, which means this crash happens when a player's data is being saved.
When a player joins a server, the `spawnBalloons()` method spawns the balloons that were attached to the player.

Therefore, it cannot be the fault of the `spawnBalloons()` method because it's a method called during connection, and the crash is happening during disconnect.

**Comment by GAsplund** [comment]
Unfortunately for me, the issue was not in relation to Endergetic. The server ran for hours without issue after it was removed, until it crashed with the exact same issue just recently. My only guess is that it is being caused by the other mixins it's referring to in the stacktrace.

Closing this issue due to not being related to this mod.
