### ISSUE TITLE
something do with the endergetic fire

### ISSUE THREAD

**Issue by Klouver0X** [team-abnormals/endergetic#179]
https://paste.gg/p/anonymous/ef9bf2147a9b4bd0b10f45170c59f272

**Comment by judicius** [comment]
Also now getting this error. This started to occur after updating Outer End to 0.2.12 which was the fix for the abnormals core update. 

MC 1.16.5
Forge 36.1.31
abnormals core 3.2.0
outer end 0.2.12
endergetic 3.0.0

Crash 1 log: https://gist.github.com/judicius/21d4903cfb3a08caf97023c845aea86a
Crash 2 log: https://gist.github.com/judicius/34b5f9d95091632f1a5aec07452d940f

**Comment by NJL5390** [comment]
I'm also getting this issue. It seems to be related to the tag for blocks which can hold ender fire. I can't seem to reproduce this with only endergetic. So maybe it's a compatibility issue between mods? 

Here's my most recent Crash Report: https://gist.github.com/NJL5390/1f30282564dfac5b75f4e77acf689c6f

**Comment by SmellyModder** [comment]
This crash looks to be caused by another mod adding incorrect entries to the `endergetic:ender_fire_base_blocks`.

**Comment by NJL5390** [comment]
It is definitely Outer End that is the cause of this. Removing that mod fixes this issue for me. I've opened an issue on their repository here: https://github.com/BlueDuckYT/The-Outer-End/issues/47
