### ISSUE TITLE
Boofloo vest keybinds don't work properly

### ISSUE THREAD

**Issue by Explode007** [team-abnormals/endergetic#181]
Greetings, I wanted to let you guys know that the booflo vest doesn't work with space bar. The separate keybind it has, if it conflicts with anything it won't make the vest pop. Not only that, but to use the second keybind you also have to hold down spacerbar. I don't know if its intentional or not but I obviously do like the idea of just pressing the space bar instead of two buttons tho the two buttons could be useful so you wont accidentally trigger it.

**Comment by SmellyModder** [comment]
If a keybind is conflicting with it, then obviously it won't work correctly.

I cannot reproduce the issue of needing to hold down the spacebar if the keybind is changed, but I've got a guess why that might be happening for you.
The Booflo Vest requires that a player must not be flying. This got added so that players that are flying can boost with the spacebar without activating the vest. With this in mind, I believe that somehow you are considered flying, which is not an issue on Endergetic's side.
