### ISSUE TITLE
Crash in poise forest (MC 1.16.5)

### ISSUE THREAD

**Issue by FastBoye127** [team-abnormals/endergetic#190]
Entering the poise forest causes a consistent crash, opening the world again causes it to crash within a few seconds.
https://pastebin.com/jXshPKdd

**Comment by SmellyModder** [comment]
This crash report is pretty strange.
It's crashing on line 120 in `BolloomFruitEntity` because the `BlockState` at the fruit's bud position doesn't have the `BolloomBudBlock#OPENED` property which should be impossible. After all, the first check ensures the block at the bud position is a `BolloomBudBlock`.
One way this could happen is if the value of `this.world.getBlockState(budPos)` changed after the first condition was processed in the if statement on line 120, but that should also not be happening.
I think there's a mod you're using that is causing these issues to occur.
A similar issue started happening with Buzzier Bees: https://github.com/team-abnormals/buzzier-bees/issues/151

**Comment by SmellyModder** [comment]
This issue looks to be an issue caused by another mod.
I'm going to close this due to the lack of activity and evidence to support this issue is directly caused by Endergetic.
If any new information about this issue pops up that points to it possibly being an issue on Endergetic's side, I will reopen it.
